---

- name: update bashrc with spark home
  lineinfile:
    path: "{{ usr_dir }}/.bashrc"
    line: 'export SPARK_HOME=#home/spark'
    state: present
  become: yes

- name: Update bashrc with all home
  become_user: "{{ autoid_user }}"
  replace:
    path: '{{ usr_dir }}/.bashrc'
    regexp: "{{ item }}"
    replace: "{{ home_dir }}"
  with_items:
  - '#home'

- name: update bashrc pyspark home
  lineinfile:
    path: "{{ usr_dir }}/.bashrc"
    line: 'export PYSPARK_PYTHON=/usr/local/bin/python3.10'
    state: present
  become: yes

- name: update bashrc java home
  lineinfile:
    path: "{{ usr_dir }}/.bashrc"
    line: 'export JAVA_HOME=/etc/alternatives/jre_11_openjdk'
    state: present
  become: yes

- name: update bashrc path
  lineinfile:
    path: "{{ usr_dir }}/.bashrc"
    line: 'export PATH=$JAVA_HOME/bin:$PATH'
    state: present
  become: yes

- name: source env
  become_user: "{{ autoid_user }}"
  shell:
    source "{{ usr_dir }}"/.bashrc

