---

- name: check Python3.10 install
  become: yes
  ansible.builtin.stat:
    path: "/usr/local/bin/python3.10"
  register: check_python

- name: Download python3.10
  become_user: "{{ autoid_user }}"
  get_url:
    url: https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz
    dest: '{{ home_dir }}'
  when: not check_python.stat.exists

- name: Extract python3.10
  become: yes
  ansible.builtin.unarchive:
    src: "{{ home_dir }}/Python-3.10.12.tgz"
    dest: "{{ home_dir }}"
    remote_src: yes
  when: not check_python.stat.exists


- name: chown of Python
  shell:
    sudo chown -Rf "{{ autoid_user }}":"{{ autoid_group }}"  "{{ home_dir }}"/Python-3.10.12
  become: yes
  when: not check_python.stat.exists

- name: config Python for make
  become_user: "{{ autoid_user }}"
  ansible.builtin.shell: "{{ home_dir }}/Python-3.10.12/configure --enable-optimizations"
  args:
    chdir: "{{ home_dir }}/Python-3.10.12"
  when: not check_python.stat.exists

- name: make python
  become: yes
  ansible.builtin.shell: sudo make altinstall
  args:
    chdir: "{{ home_dir }}/Python-3.10.12"
  when: not check_python.stat.exists

- name: check old python3
  become: yes
  ansible.builtin.stat:
    path: /usr/bin/python3
  register: check_python3

- name: remove old python
  shell:
    rm -rf /usr/bin/python3
  become: yes
  
- name: python soft link
  shell:
    ln -s /usr/local/bin/python3.10 /usr/bin/python3
  become: yes

- name: update bashrc
  lineinfile:
    path: "{{ usr_dir }}/.bashrc"
    line: 'export PYSPARK_PYTHON=/usr/local/bin/python3.10'
    state: present
  become: yes

- name: source env
  become_user: "{{ autoid_user }}"
  shell:
    source "{{ usr_dir }}"/.bashrc

- name: check pip link
  become: yes
  ansible.builtin.stat:
    path: "/usr/bin/pip"
  register: check_pip

- name: pip soft link
  shell:
    sudo ln -s /usr/local/bin/pip3.10 /usr/bin/pip
  become: yes
  when: not check_pip.stat.exists

- name: check python download
  become: yes
  ansible.builtin.stat:
    path: "{{ home_dir }}/Python-3.10.12.tgz"
  register: check_file

- name: delete python dowload
  shell:
    rm "{{ home_dir }}"/Python-3.10.12.tgz
  when: check_file.stat.exists
  become: yes


